//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.OrderFoods = new HashSet<OrderFood>();
        }
    
        public int FoodId { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int FoodCategoryId { get; set; }
        public string Photo { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFood> OrderFoods { get; set; }
        public string GetPhoto
        {
            get
            {
                return $"{Directory.GetCurrentDirectory()}\\images\\{this.Photo ?? "default.jpg"}";
            }
        }
    }
}
