//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFood
    {
        public int OrderFoodId { get; set; }
        public int OrderId { get; set; }
        public int FoodId { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
