//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ChangeEmployees = new HashSet<ChangeEmployee>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public int UserRoleId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeEmployee> ChangeEmployees { get; set; }
        public virtual Role Role { get; set; }
        public string GetPhoto
        {
            get
            {
                return $"{Directory.GetCurrentDirectory()}\\images\\{this.Photo ?? "default.jpg"}" ;
            }
        }
    }
}
